name: .NET Build & UnitTests

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  
env:
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 10.0.x
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  WORKING_DIRECTORY: src
  TESTING_DIRECTORY: src

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v6.0.2

    # - name: 💴 Cache
    #   id: cache-nuget
    #   uses: actions/cache@v3.3.2
    #   with:
    #     path: ${{ env.NUGET_PACKAGES }}
    #     key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
    #     restore-keys: |
    #       ${{ runner.os }}-nuget-
    # - name: ❔ Cache Hit ${{ steps.cache-nuget.outputs.cache-hit }}
    #   run: |
    #     echo "→ ${{ steps.cache-nuget.outputs.cache-hit }}"

    - name: ✨ Setup .NET
      uses: actions/setup-dotnet@v5.2.0
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    # - name: 🏦 Restore with lock files
    #   run: dotnet restore "${{ env.WORKING_DIRECTORY }}" --locked-mode
    - name: 🏦 Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: 🛠️ Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: 🧪 Test
      run: dotnet test "${{ env.TESTING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal --filter Category!=local
